version: '3'

services:
  php:
    build: 
      context: ./docker/php-fpm
    volumes:
      - ./:/var/www/odds:delegated

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./:/var/www/odds:delegated
      - ./docker/nginx/etc/default:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/etc/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/etc/certs:/etc/certs
    ports:
      - "5441:5441"
    links:
      - php      
    depends_on:
      - php
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - 3309:3306
    environment:
      - 'MYSQL_ROOT_PASSWORD=pass'
      - 'MYSQL_DATABASE=test'  
    volumes:
      - ./docker/mysql:/var/lib/mysql
